import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';
import Banner from '../src/modules/Banner';
import ScrollSequence from '../src/modules/ImageSequence';
import { exterior1 } from 'public/assets/seq/seq';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import { EngineSection } from '@src/components/EngineSection';
import { SwiperSection } from '../src/components/SwiperSection';
import ParallaxSection from '@src/components/parallex';
import ParallaxSectionSecond from '@src/components/parallex2';
import { EngineTypesSection } from '@src/components/EngineTypes';
import AmbiantLight from '@src/components/ambiant';
import VRShowroom from '@src/modules/VRShowroom';
import Dimensions from '@src/components/dimensions';
import KiaConnect from '@src/components/kiaConnect';
import Specs from '@src/components/specs';

export default function Home() {
  const { t } = useTranslation('common');
  const [selectedFeature, setSelectedFeature] = useState(0);
  const isArabic = false; // Replace with your actual language detection logic
  const [mounted, setMounted] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false)

  const router = useRouter();
  const { locale, query } = useRouter();
  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) {
    return null; // or a loading state
  }



  return (
    <main className="relative">

      <Head>
        {router.locale == 'ar' ? <title>كيا تاسمان - البروشور الرقمي</title> : <title>Kia Tasman - Digital Brochure</title>}
        <link rel="icon" href="/kia.ico"  />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Banner />
      <EngineSection />
      <div className="relative" style={{ zIndex: 1000 }}>
        <ScrollSequence
          id="canvas4"
          imagesUrl={exterior1}
          totalFrames={exterior1?.length}
          text={t('led_rear_lamps')}
          description={t('led_rear_lamps_description')}
          endTextFrame={100}
          text2={t('fastback_design')}
          description2={t('fastback_description')}
          startTextFrame={30}

          startTextFrame2={120}
          endTextFrame2={exterior1?.length}
        />
      </div>
      <SwiperSection id={0} />

      <div className="relative" style={{ zIndex: 1000 }}>
        <ScrollSequence
          id="canvas4"
          imagesUrl={exterior1}
          totalFrames={exterior1?.length}
          text={t('led_rear_lamps')}
          description={t('led_rear_lamps_description')}
          endTextFrame={100}
          text2={t('fastback_design')}
          description2={t('fastback_description')}
          startTextFrame={30}

          startTextFrame2={120}
          endTextFrame2={exterior1?.length}
        />
      </div>
      <AmbiantLight isModalOpen={isModalOpen} setIsModalOpen={setIsModalOpen} />

      <SwiperSection id={1} />
      <VRShowroom />
      <ParallaxSection />
      <EngineTypesSection />

      <ParallaxSectionSecond />
      <div className=' bg-white '>
        <SwiperSection id={3} noBg dark={true} />
      </div>
      <KiaConnect/>
      <Dimensions />
      <Specs/>
      {isModalOpen ?
        <div className='fixed w-screen h-screen bg-black/90 z-[10000] flex flex-col items-center justify-center  left-0 top-0'>
          <div className="bg-white rounded-xl flex flex-col  items-end w-[500px]  relative" >
            <button onClick={() => {
              document.body.style.overflow = 'auto'
              setIsModalOpen(false)
            }} className="text-black text-3xl rounded-full w-10 h-10 bg-white absolute end-4 top-4 ">×</button>
            <div className='flex flex-col items-center  w-full'>
              <img src={isModalOpen == 1 ? 'https://methods.ae/wp-content/uploads/ktk-panoramicdisplay.jpg' : isModalOpen == 2 ? 'https://methods.ae/wp-content/uploads/ktk-dualwirelesscharger.jpg' : isModalOpen == 3 ? 'https://methods.ae/wp-content/uploads/ktk-consoletable.jpg' : 'https://methods.ae/wp-content/uploads/ktk-walkinswitch.jpg'} width={'100%'} height={'70%'} alt="Analytics Overview" className="rounded-t-xl" />
              <div className="p-6 flex flex-col gap-3 ">
                <div className="text-[#333] text-center font-[InterBold] text-[20px]">{isModalOpen == 1 ? 'Panoramic Integrated Display' : isModalOpen == 2 ? 'Dual Wireless Charger' : isModalOpen == 3 ? 'Console Table' : 'Passenger Walk-in Switch'}</div>
                <div className="text-[#666]  text-center font-[InterRegular] text-sm">{
                  isModalOpen == 1 ? `Enjoy the brand's state-of-the-art infotainment system with the widest display in its class. You can also maintain your vehicle to the latest through OTA Update.` : isModalOpen == 2 ? `Comprehensive user management system with role-based access control and activity tracking across your platform.` : isModalOpen == 3 ? `An expandable console table turns the Kia Tasman into a private mobile office. Unfold the upper part of the console armrest to create a wide table you can use for checking your laptop or documents—or enjoying a simple meal.` : `This function allows you to adjust the forward/backward position and angle of the passenger seat from the driver's seat or the rear seat to improve the convenience of getting in and out of the vehicle and living in the rear seat.`
                }</div>
              </div>
            </div>
          </div>
        </div> : null}
    </main>
  );
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
    },
  };
}
